### ISSUE TITLE
Pywebdriver on Ubuntu 22.04

### ISSUE THREAD

**Issue by quentinDupont** [akretion/pywebdriver#100]
Ubuntu 22.04 is officialy out.
What about compatibility with Pywebdriver.
This is not an incentive to work but just a space to discuss and to share if someone try to install and run it on this version :-)

**Comment by nwinkelstraeter** [comment]
I don't think there should be any compatiblity problems with ubuntu 22.04 but the packaging and the build scripts need some changes.

I think at least these changes would be neccessary
- [ ] `dh-systemd` is not available in 22.04 -> bump debian/compat from 9 to 11, remove --with systemd
- [ ] `dh-virtualenv` ist not available for 22.04 in ppa:jyrki-pulliainen (but it's now available in ubuntu repos)
- [ ] adjust build.sh and github actions

**Comment by quentinDupont** [comment]
Hello !
I start to have some clients with Ubuntu 22.04 and I'm still incompetent technically for pywebdriver :laughing: 
But i'm ready to help testing a new version for Ubuntu 22.04 !

**Comment by quentinDupont** [comment]
@PierrickBrun showed me how it works, i'm gonna try to get forward on this as soon as possible

**Comment by quentinDupont** [comment]
PR in progress here : https://github.com/akretion/pywebdriver/pull/110
But it don't have printer for the moment to test it (neither Ubuntu 22) If someone wants to test it ?

**Comment by PierrickBrun** [comment]
The ubuntu 22.04 version is available in the latest release
