### ISSUE TITLE
A new release to support Mettler Toledo 8217 for Windows?

### ISSUE THREAD

**Issue by baimont** [akretion/pywebdriver#118]
Hi

I tested pywebdriver for a Mettler Toledo Ariva on Ubuntu after https://github.com/akretion/pywebdriver/pull/102 was merged.

It works fine, thanks!

I then tried to use it on Windows 10, using last release (https://github.com/akretion/pywebdriver/releases/download/v3.0.11/pywebdriver_win64.zip) but as I understand the feature was merged on Oct 10, 2022 and the latest version was released on Sep 29, 2021 so it doesn't contain the feature.

Would it be possible to release a version so that this feature is available on Windows?

Thanks!

**Comment by rousseldenis** [comment]
@PierrickBrun

**Comment by PierrickBrun** [comment]
Hi @baimont ,

I've just created a new release can you confirm me that it works with this device on windows ?

**Comment by baimont** [comment]
> Hi @baimont ,
> 
> I've just created a new release can you confirm me that it works with this device on windows ?

Hi @PierrickBrun,

As soon as I've tested I'll let you know.

Thanks!

**Comment by baimont** [comment]
> > Hi @baimont ,
> > I've just created a new release can you confirm me that it works with this device on windows ?
> 
> Hi @PierrickBrun,
> 
> As soon as I've tested I'll let you know.
> 
> Thanks!

Hi @PierrickBrun,
I tested on a virtual machine and it does not work at the moment. I'm waiting for a real machine to test again.
Here is what I observed:

First, after I ran generate_certificates.bat it did not create two files in C:\pywebdriver. Instead they where generated in the folder the script is. So I manually created a pywebdriver folder in C:. And then I moved extracted files in the new folder.

Then I adapted the config file and launched the install script (as my user and as admin).
As localhost:8069 was not reachable I rebooted but pywebdriver stayed inaccessible after reboot. Either install script does not work either I do something wrong.
So to access the web interface I launched pywebdriver application file. This works.

On the web interface page http://localhost:8069/usb_devices.html gives me an internal server error. I managed to get a stacktrace:
[2023-02-20 11:50:38,335] ERROR in app: Exception on /usb_devices.html [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask_cors\extension.py", line 165, in wrapped_function
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "pywebdriver\views.py", line 70, in usb_devices
IndexError: list index out of range

And here is my main problem: I couldn't get to launch pywebdriver with the scale config.

To be sure my devices where connected, I used:

C:\Users\alfresco>py -m serial.tools.list_ports -v
COM4
    desc: BCD-2000 USB Serial Port (COM4)
    hwid: USB VID:PID=1504:008C SER=00000000000000A
COM5
    desc: Périphérique série USB (COM5)
    hwid: USB VID:PID=0EB8:2200 SER=SER_CDC LOCATION=1-4
2 ports found

So COM4 is my displayer and COM5 is my scale.

If I use a config without scale_driver, pywebdriver works.

If I use the following config, pywebdriver cannot launch.
[application]
print_status_start=false
drivers=odoo8,display_driver,scale_driver

[display_driver]
device_name=COM4
device_rate=9600
device_timeout=0.05

[scale_driver]
protocol_name=mettler_toledo_8217
poll_interval=0.5
port=COM5
baudrate=9600

I recorded my screen and was able to get the error message before the executable window closed:
![image](https://user-images.githubusercontent.com/32102436/220087807-49570303-1db7-44ab-9a3f-b2a4d8e2c1a4.png)

**Comment by sbidoul** [comment]
It looks like the /usb_devices route https://github.com/akretion/pywebdriver/blob/878fe2b8fceb77014f97913edbbaacc7a86d4cc5/pywebdriver/views.py#L61 attempts to call the lsusb command which is likely not available on Windows? But that should not prevent pywebdriver to start?

@baimont are you sure `scale_driver.py` is present in the plugins directory? Because your screenshot (ModuleNotFoundError) tends to indicate it is missing.

**Comment by PierrickBrun** [comment]
Hi @baimont ,

Thank you for this very detailed report. Windows usage lacks documentation, sorry about that.

The .bat scripts are meant to be used from the unzipped files. It can be anywhere you like.

The generate_certificate.bat file must be run as the current user and the install.bat script must be run as administrator.

About the usb_devices.html view, this is a bug in windows that should be addressed:
https://github.com/akretion/pywebdriver/blob/master/pywebdriver/views.py#L63 
This line cannot work in windows and it should be easily fixed.

about the fact that pywebdriver won't start with scale_driver plugin. This comes from the fact that this plugin is not referred here: https://github.com/akretion/pywebdriver/blob/master/pywebdriver/plugins/__init__.py#L6 
I think this should prevent the scale from working on all OS.


PS: thanks @sbidoul  for you answers, I've just seen them after writing this. I'll post it anyways if it can help

**Comment by sbidoul** [comment]
@PierrickBrun @baimont actually, it seems the `plugins` directory is entirely missing from `pywebdriver_win64.zip`.

**Comment by sbidoul** [comment]
Ah, right, sorry for the noise.

So I inspected `pywebdriver.exe` with pyinstaller's `pyi-archive_viewer` and it seems that scale_driver is missing from the plugins directory. May be it needs to be declared here? https://github.com/akretion/pywebdriver/blob/878fe2b8fceb77014f97913edbbaacc7a86d4cc5/windows/pywebdriver.spec#L29-34

**Comment by PierrickBrun** [comment]
Good catch ! I totally forgot about the hidden imports.

This should be the reason, I'll make a fix.

The problem is that I can't test is on windows since I don't have a VM on hand

**Comment by baimont** [comment]
> Good catch ! I totally forgot about the hidden imports.
> 
> This should be the reason, I'll make a fix.
> 
> The problem is that I can't test is on windows since I don't have a VM on hand

Thanks @PierrickBrun and @sbidoul 
@PierrickBrun can you make a release after the fix? I'll test it directly this time.

**Comment by PierrickBrun** [comment]
@baimont The release is ready.

I've included an installer for windows, can you check this ? :)

If you use the installer and want to change the config.ini you need to install it and then modify the file. After that you need to restart the service for it to be taken into account.
To restart the service you can find Pywebdriver with the "services" windows app and restart it.
You can also run "uninstall.bat" and "install.bat" as administrator

**Comment by baimont** [comment]
> @baimont The release is ready.
> 
> I've included an installer for windows, can you check this ? :)
> 
> If you use the installer and want to change the config.ini you need to install it and then modify the file. After that you need to restart the service for it to be taken into account. To restart the service you can find Pywebdriver with the "services" windows app and restart it. You can also run "uninstall.bat" and "install.bat" as administrator

Thanks @PierrickBrun !
Just tested on a real machine this time.
The installer works fine.

There is an other stacktrace now when I try to connect to the web interface:
Traceback (most recent call last):
  File "flask\app.py", line 2551, in __call__
  File "flask\app.py", line 2531, in wsgi_app
  File "flask_cors\extension.py", line 165, in wrapped_function
  File "flask\app.py", line 2528, in wsgi_app
  File "flask\app.py", line 1815, in full_dispatch_request
  File "pywebdriver\plugins\scale_driver.py", line 135, in before_first_request
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pywebdriver.plugins.scale_protocols'

**Comment by baimont** [comment]
> I've fixed it again. I hope this is the last one

Ok @PierrickBrun, thanks!
I'll begin with this test tomorrow morning. 🤞

**Comment by baimont** [comment]
Hi @PierrickBrun,

I get the same error as yesterday morning, before your first fix.

![image](https://user-images.githubusercontent.com/32102436/220293793-6e7fc758-4e3f-46ab-9959-3d40e5f60e8e.png)

In your last fix
 https://github.com/akretion/pywebdriver/commit/cc4769914da1214a8af75778cefbf184c167908d
you removed pywebdriver.plugins.scale_driver. So I guess you should put it back?

**Comment by PierrickBrun** [comment]
Indeed... Release in progress

**Comment by baimont** [comment]
> > Indeed... Release in progress
> 
> ModuleNotFoundError ModuleNotFoundError: No module named 'pywebdriver.plugins.scale_protocols.mettler_toledo_8217'
> 
> Traceback (most recent call last) File "flask\app.py", line 2551, in **call** File "flask\app.py", line 2531, in wsgi_app File "flask_cors\extension.py", line 165, in wrapped_function File "flask\app.py", line 2528, in wsgi_app File "flask\app.py", line 1815, in full_dispatch_request File "pywebdriver\plugins\scale_driver.py", line 135, in before_first_request File "importlib__init__.py", line 127, in import_module File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 984, in _find_and_load_unlocked ModuleNotFoundError: No module named 'pywebdriver.plugins.scale_protocols.mettler_toledo_8217'

Any idea @PierrickBrun, @sbidoul ?
I tried this:
Modifying windows/pywebdriver.spec to include pywebdriver.plugins.scale_protocols.mettler_toledo_8217 
And then, as I understood from .github/workflows/main.yml, packaging using pyinstaller.exe and installing using innosetup but I still get the same error.
