### ISSUE TITLE
Baxtran TW Toledo Scale offline in odoo

### ISSUE THREAD

**Issue by ferdymercury** [akretion/pywebdriver#124]
Hello,
I am using a Toledo scale over COM1 on Windows, direct communication works well.
![IMG_20230307_152416592](https://user-images.githubusercontent.com/10653970/223463648-889065dd-2a5d-4c71-b379-b662b24d5620.jpg)
I configured pywebdriver 3.0.18 and scale is well recognized.
![IMG-20230307-WA0001](https://user-images.githubusercontent.com/10653970/223464499-72254054-9b2b-42d1-92d3-8af10985d155.jpeg)
I then configured Odoo12 Point of Sale IOT box.
![IMG_20230307_153304365](https://user-images.githubusercontent.com/10653970/223464934-c029ce9e-aeb8-448a-86d9-172ca384dcaa.jpg)

However, in the POS I tried clicking on a weighable product. The screen appears filled with zeros even if there were 100g on the scale.

If I click on the proxy icon it says Scale Offline.
![IMG_20230307_153825123](https://user-images.githubusercontent.com/10653970/223465359-a955b969-8f77-4b68-91d1-7749d9f71a28.jpg)
![IMG_20230307_153829206](https://user-images.githubusercontent.com/10653970/223465342-f517e865-7105-4841-82f5-0e61f5f1e5f8.jpg)

Is there anything I am doing wrong, maybe @PierrickBrun or @huguesdk know?
Any help is welcome. Thanks in advance.

**Comment by PierrickBrun** [comment]
Hi @ferdymercury ,

This is most probably a problem of communication between pywebdriver and Odoo, you should look into the Network tab of the dev tool of your browser to check what's happening.

I'm not sure if this is the case in the 12.0 version of Odoo but you may have to check the "receipt printer" in the pos config. Sometimes Odoo only tries to communicate if this is checked.

**Comment by ferdymercury** [comment]
Thanks, I will try to see if there any error messages in the Network tab, and try to connect also the receipt printer, but it goes through USB, so I am not sure if it will fail thus because of the Windows bug (it appears though in the win32_printer drivers).

In case I do not find the solution, @huguesdk mentioned that some 'paid support service' could be offered to configure this. What would be the rought budget for this? Thanks in advance.

**Comment by huguesdk** [comment]
@ferdymercury please contact us at info@coopiteasy.be (in french or english) to discuss the conditions.

**Comment by ferdymercury** [comment]
@PierrickBrun one update from my side. Thanks for the suggestions.

We managed to connect the receipt printer and cashdrawer, as you suggested. It works well, it prints and opens when we validate the order. However the scale fails to measure any weight...

We also looked into the browser dev tools. We got:
![IMG_20230310_150930093](https://user-images.githubusercontent.com/10653970/224395244-5b1f852e-91e0-48c3-bdb6-ac84d294c02a.jpg)
And
![IMG_20230310_151001573](https://user-images.githubusercontent.com/10653970/224397992-dc4969cc-c1c0-48e4-b96c-8f4920f48dbf.jpg)

And
![IMG_20230310_150943852](https://user-images.githubusercontent.com/10653970/224395451-4a1d2942-20f1-44ee-9b49-c37bcea5c290.jpg)

I managed to solve the 42 warnings about network requests by adding an exception to the HKEY windows registry Chrime policies. No I do not get warnings but scale still fails. Any other log file I can check? We tried with Chrome Edge Firefox, same result for all three.

Could the issue be some different line endings on Windows vs Linux?

Pywebdriver seems to work well and connects with scale and prints correctly via escpos:
![16784733305131240700610115517549](https://user-images.githubusercontent.com/10653970/224397599-6808c9c4-b2f1-4326-be73-1c4e4288204e.jpg)

**Comment by PierrickBrun** [comment]
Hi @ferdymercury , can you check with @huguesdk ? This is getting too specific to be fixed in an issue

**Comment by ferdymercury** [comment]
Yes, I am in contact with Hugues, we are discussing the conditions.

On the other hand, I think I already found the culprit.

My balance returns the following code for the weight in gram: `00135` without any dot. It always returns grams.

As a consequence, the REGEX expression fails to capture this:
```
ANSWER_RE.match(rb'00123') ---> None
```
compared to:
```
ANSWER_RE.match(rb'00.123') ---> <re.Match object; span=(0, 6), match=b'00.123'>
```

Could I provide a PR to handle this case in a new baxtran_toledo protocol plugin? I would divide the result by 1000 so that the final result is in kg
