### ISSUE TITLE
Nitpicking doc

### ISSUE THREAD

**Issue by bealdav** [akretion/pywebdriver#130]
Doc here let think you can install it on debian
https://github.com/akretion/pywebdriver#install-ubuntu

![image](https://user-images.githubusercontent.com/1853434/233007003-75cd0343-791b-43a4-8577-e6c9a3877278.png)

----

But this code https://github.com/akretion/pywebdriver/blob/master/debian/install.sh#L8

require to have `UBUNTU_CODENAME` string in the distribution.
Debian has not that string.
A customer of mine tried but fails with debian

Maybe it's better to define in doc that supported versions are only ones used in github actions.

What do you think ?

**Comment by hparfr** [comment]
Yes, can you provide a patch with `lsb_release -a` ?

**Comment by legalsylvain** [comment]
Hi @bealdav. What is the state of this issue ?

**Comment by bealdav** [comment]
I need to talk to @PierrickBrun here
