### ISSUE TITLE
Using more than 1 printers

### ISSUE THREAD

**Issue by ghacosta** [akretion/pywebdriver#131]
is it possible to set more than one printers? I've set one succesfully and currently using on odoo but now I want to add a second one as receipt printer but it is not recognized as escpos printer (it's a generic printer, drivers installed and I've been using it as escpos printer for a while without issues).

- Printer 1 (epson-like) is named in Windows as "escpos", working fine.
- Printer 2 is named in Windows as "escpos2", not being detected as escpos but listed on first collumn win32print.

I'm bringing this because this line on `config.ini` suggest that more than one printer can be set.
```
[escpos_driver]
...
printer_names=escpos,escpos*,EPSON TM-T20 Receipt*,EPSON TM-P20 Receipt*,EPSON TM*
```

**Comment by ghacosta** [comment]
Another idea would be running another instance of pywebdriver on a different port, how can it be done?

**Comment by legalsylvain** [comment]
Hi @ghacosta. Thanks for your interest in pywebdriver.

1) I never saw such usage. As i developped the escpos driver (adapted from odoo code), I don't remember having allowed such possibiilities.

2) I don't undertsand very well what are your usage ? What are the models of your two printers and what the usage for each one ? 

Thanks !

> I'm bringing this because this line on config.ini suggest that more than one printer can be set.

I don't see the ``printer_names`` key in the ``config.ini`` file. Do you talk about the same file ? 

https://github.com/akretion/pywebdriver/blob/master/config/config.ini.tmpl

regards.

**Comment by ghacosta** [comment]
Hi @legalsylvain thanks for answering!

I've installegd [pywebdriver_win64_installer.exe](https://github.com/akretion/pywebdriver/releases/download/v3.0.18/pywebdriver_win64_installer.exe) on a W10 and works just fine for a general 80mm epson-like printer.

The thing is I'd like to use a second order printer let's say for the kitchen but this second printer (a generic POS-58 thermal receipt printer that is sold as a unbranded device) which is connected via USB to my computer where runs pywebdriver it is not being listed under escpos but under win32print.

So my question is, pywebdriver is meant to use only one printer via proxy at a time? or how can I setup to have more than one printer connected to my system?

Regarding `config.ini`, that line does show on Windows' file.

```
[escpos_driver]
device_type=win32
; use singular printer_name if you want to force using a specific name
;printer_name=escpos
printer_names=escpos,escpos*,EPSON TM-T20 Receipt*,EPSON TM-P20 Receipt*,EPSON TM*
; If your POS printer has a serial interface, comment the line above
; and uncomment the lines below
;device_type=serial
;serial_device_name=/dev/ttyS1
;serial_baudrate=9600
;serial_bytesize=8
;serial_timeout=1
```

you can check this thing by downloading the zip file [pywebdriver_win64.zip](https://github.com/akretion/pywebdriver/releases/download/v3.0.18/pywebdriver_win64.zip) and checking the file on `config/config.ini`

**Comment by legalsylvain** [comment]
Oh. I see , it's Come from that file. 

https://github.com/akretion/pywebdriver/blob/master/windows/config.ini

Well, afaik, pywebdriver doesnt allow to print on many printers. But i dont use windows installation.

@PierrickBrun could help you on that topic.

**Comment by kanys5** [comment]
@ghacosta 
I had the same problem for quite some time, trying to use multiple printers with Pywebdriver using one PC. 
The work around is quite simple, install multiple services for Pywedriver and configure each service to one specific printer at a different port, it works for me. I used this method to implement for Odoo 14 by simply including the port number to Printers in Odoo configurations.

**Comment by PierrickBrun** [comment]
`printer_names` do no allow to print to several printers at the same time, it will print to the first available printer in the list.

It is useful if some printers are not always available.

@kanys5 has a good solution to this problem
