### ISSUE TITLE
Not an issue more like an question

### ISSUE THREAD

**Issue by omariobros** [akretion/pywebdriver#135]
Is there any change to have Star (Printers) Support with Pywebdriver?

I have Star C-print3 here and I cannot find any solution to work with it unless CUPS.org server.

Regards.

**Comment by legalsylvain** [comment]
you can try to adapt the pywebdriver code for your printer if you have python skills
alternatively, you can hire a developper to do that job

there is no roadmap in pywebdriver project. Just contributions from people that need a connection to a specific hardware.
kind regards.
