### ISSUE TITLE
oca pos_payment_terminal connection telium

### ISSUE THREAD

**Issue by zapateroremendon** [akretion/pywebdriver#136]
Good day,
I can not make pywebdriver works with oca pos_payment_terminal(ingenico/telium) in odoo 14 CE neither odoo 16 EE. I believe I am missing the right "oca_payment_terminal_id"(terminal identifier) what must be fill in?
![Screenshot from 2023-06-16 17-06-29](https://github.com/akretion/pywebdriver/assets/37345629/e16174f6-4d24-4b01-b3ab-b4498eab941f)
![Screenshot from 2023-06-16 16-52-33](https://github.com/akretion/pywebdriver/assets/37345629/63cf9f28-ff60-4d3a-b6f9-e73f07c34207)

**Comment by legalsylvain** [comment]
Hi. 
In the pywebdriver test page, is it working ?

**Comment by zapateroremendon** [comment]
> Hi. In the pywebdriver test page, is it working ?

Yes, It is working, It says telium is connected, however "communication test" link is not, as depicted in second image.

**Comment by alexis-via** [comment]
@zapateroremendon OK, so it's NOT working in pywebdriver. You must first focus on make the communication test work. To help you pin-point the problem, you may want to use this small python script: https://github.com/OCA/pos/blob/12.0/hw_telium_payment_terminal/test-scripts/telium-test.py

**Comment by zapateroremendon** [comment]
Thanks for your answer @alexis-via , the output for telium-test.py is:
Opening serial port /dev/ttyACM0 for payment terminal with baudrate 9600
serial.is_open = True
Signal ENQ sent to terminal
Terminal : SAME PLAYER TRY AGAIN
Signal EOT sent to terminal
Signal ENQ sent to terminal
Terminal : SAME PLAYER TRY AGAIN
Signal EOT sent to terminal
Signal ENQ sent to terminal
Terminal : SAME PLAYER TRY AGAIN
Signal EOT sent to terminal
Closing serial port for payment terminal

Nothing is print on pos telium screen :(

**Comment by alexis-via** [comment]
An important point : the Concert/Caisse AP protocol (https://www.associationdupaiement.fr/protocoles/protocole-caisse/) is only implemented on French payment terminals. Don't expect to find it on a payment terminal in a country other than France. You seem to be from Chile... if your payment terminal is for Chile, then it doesn't support Concert/Caisse AP protocol.

**Comment by zapateroremendon** [comment]
Thanks so much for your help :+1:
