### ISSUE TITLE
not full digits print for total and change

### ISSUE THREAD

**Issue by Neurotec** [akretion/pywebdriver#14]
first thanks for this great project.

i installer from master repository, print fine but the field of **total and change**, not print full digits they cut, example:

expected: 1200.00
print total: 200.00
cut the number 1
or

expected: 199999.99
print total: 999.99
cut the first 199

what can i do?

thanks

**Comment by legalsylvain** [comment]
Hi, with with version of Odoo this bug occures ?
regards.
