### ISSUE TITLE
Switch to Python web server supporting SSL instead depending on Nginx

### ISSUE THREAD

**Issue by sylvainc** [akretion/pywebdriver#24]
Hello,

Ubuntu Debian package of Pywebdriver depends on Nginx WEB server (for serving HTTPS) it's would be interesting to switch to an embedded python web server supporting SSL (like Cherrypy, http://cherrypy.org/ or others), which would be easier to "package" on all OS (including Microsoft ones).

CC: @sebastienbeau, @alexis-via, @legalsylvain

**Comment by sebastienbeau** [comment]
I think it's a good idea to make it more simple to install

**Comment by rvalyi** [comment]
performance will hardly be as good nginx, but I think it is rarely a priority for pywebdriver, right?

**Comment by sylvainc** [comment]
Hello,

I agree, nginx for serving a few requests per minutes/hours is not a good idea in comparison of the footprint/dependencies on a desktop system, a python based web server solution seem to be more adapted, and allow more interrogations between the systems.

I have cooked a PR based on this idea (using gunicorn instead), and made it compatible with Ubuntu 18.04 LTS (https://github.com/akretion/pywebdriver/pull/29).

@andreparames  have also done some work (https://github.com/akretion/pywebdriver/pull/27) with SSL context that I think is a good idea too (that I'have not seen before starting this work...). Maybe It's a good idea to make it complementary because gunicorn is not designed to Windows based systems.

Thanks!
