### ISSUE TITLE
Have not access rights

### ISSUE THREAD

**Issue by alejandroperezcosio** [akretion/pywebdriver#3]
Hello, I would really like to use pywebdriver to emulate a POSBox but I'm getting this error: 
![error](https://cloud.githubusercontent.com/assets/5828213/7778940/1ec520e4-009e-11e5-8dd8-2f900a50bfac.png)
Do you know what's happening and how to fix it?
- I have the printer connected and started
- My user is part of plugdev group
- I'm running from virtualenv

**Comment by legalsylvain** [comment]
I guess it's a duplicate of #15.
