### ISSUE TITLE
Deprecated flask import flask.ext.babel

### ISSUE THREAD

**Issue by alexis-via** [akretion/pywebdriver#37]
Pywebdriver doesn't work with the latest versions of Flask. On versions of flask packaged in Ubuntu 18.04, it still works but there is this warning:

/usr/local/src/pywebdriver/pywebdriver/__init__.py:33: ExtDeprecationWarning: Importing flask.ext.babel is deprecated, use flask_babel instead.

This import needs to be fixed.

**Comment by legalsylvain** [comment]
could you provide the version numbers that works and doesn't work ?
regards

**Comment by rousseldenis** [comment]
Solved by #29

@alexis-via @PierrickBrun  Closing this ?
