### ISSUE TITLE
[RFC] Support for python3

### ISSUE THREAD

**Issue by rousseldenis** [akretion/pywebdriver#38]
@PierrickBrun @legalsylvain 
Could we reasonably try to port pywebdriver to python3 support ?
I can manage to see if it does not imply too much changes.

**Comment by PierrickBrun** [comment]
I think we can but I have no idea of much time is needed.
This will be necessary because Python2 won't be included in Ubuntu 20.04 LTS

**Comment by bealdav** [comment]
I'm in favor to port to 3. If you decide to 3, I can help on some parts

**Comment by rousseldenis** [comment]
With some minor changes, I can make (with my driver) it run.

I will make a PR for that.

**Comment by rousseldenis** [comment]
#39

**Comment by sbidoul** [comment]
IMHO we can even make it python3 only and abandon python2 support in pywebdriver.

**Comment by bealdav** [comment]
ok for me

**Comment by alexis-via** [comment]
Pywebdriver works well on python3 now (master branch), so let's close this old ticket.
