### ISSUE TITLE
Epson TM-T20III non reconnu

### ISSUE THREAD

**Issue by tadjiddine** [akretion/pywebdriver#51]
Bonjour,

Je viens de changer d’imprimante de caisse
Avant: Epson TM-T20II
Maintenant : Epson TM-T20III
Depuis le changement l’imprimante et détecté hors ligne par odoo.

J’ai complètement désinstallé puis réinstaller pywebdriver, sans succès.

Avez-vous une idée de la source du problème ??

![image](https://user-images.githubusercontent.com/61819516/92695938-71cda780-f35e-11ea-9507-0e1f9b0bcb0c.png)

![image](https://user-images.githubusercontent.com/61819516/92695811-42b73600-f35e-11ea-9a67-cbe338567d39.png)

**Comment by legalsylvain** [comment]
Hi @tadjiddine. did you installed with the last commit ? https://github.com/akretion/pywebdriver/commit/59178c1b1d7ccca6aaea3868dc63761ac6753484

thanks.

**Comment by tadjiddine** [comment]
Bonjour et merci pour réactivité.
actuellement j'ai la version  (pywebdriver_20191009_amd64.deb) installé via la commande : " apt install pywebdriver"
j'ai essayé d'installer la version "59178c1" mais le guide d'installation n'est pas à jour.
voici  les commandes que j'ai exécuté :
 "pip3  install -r requirements.txt"
 "python  pywebdriverd"
Apres avoir configuré le fichier config/config.ini 

avez-vous une procédure à jour, d'installation de la version "59178c1" pour que je puisse tester

merci d'avance

**Comment by legalsylvain** [comment]
dans la mesure ou le commit date de Mars 2020, je pense que la version que tu as est obsolète. Il faut voir avec @PierrickBrun, @sylvainc d' akretion pour le packaging.

**Comment by bealdav** [comment]
#quickanddirty solution fix missing line in you server while waiting a new release

**Comment by legalsylvain** [comment]
> #quickanddirty solution add missing python line in your server while waiting a new deb release

No, a lot of file changed. it is not possible to patch as you say. the variable ``SUPPORTED_DEVICES`` doesn't exist.

We need to repackage this apps. @PierrickBrun, @sylvainc : Do you think it's possible ? 

thanks.

**Comment by bealdav** [comment]
You're right sylvain,
Probably that github sponsor could be very efficient here to make update more smoothly ?
SUPPORTED_DEVICES could be completed configuring .ini files (empty by default) and consumed by script freeing specified device.

Additional COMMUNITY_TESTED_SUPPORTED_DEVICES might be useful as additional information provided by community but not really tested by maintainers ?

Just some ideas, maybe not the best ones but that could help to find better.

**Comment by legalsylvain** [comment]
>  Probably that github sponsor could be very efficient here to make update more smoothly ?

some times ago, the idea was to set this project under OCA umbrella. Did you changed your mind at akretion ?  

>  SUPPORTED_DEVICES could be completed configuring .ini files (empty by default) and consumed by script freeing specified device.

Yes, it could be a great move, but the problem, here is that the ``.deb`` file is fully outdated. not only this configuration, but one year of work is missing. We need a repackaging IMO. Refactoring can come later.

**Comment by PierrickBrun** [comment]
I'll try to publish a new one soon but I can only update this package https://github.com/akretion/pywebdriver/tree/master#installation-on-ubuntu-1804-new and not the old one.

I think a simpler approach is to generate .deb and put them in github releases

**Comment by tadjiddine** [comment]
Bonjour,
Merci à tous pour vos interventions.

> J'essaierai d'en publier un nouveau bientôt, mais je ne peux mettre à jour que ce package https://github.com/akretion/pywebdriver/tree/master#installation-on-ubuntu-1804-new et non l'ancien.

J'attend avec impatience la publication, car je vous avoue que je suis complètement bloqué avec mon TPV qui n'imprime plus de ticket.

> Je pense qu'une approche plus simple consiste à générer .deb et à les mettre dans les versions github

Si vous avez les lignes de commande permettant de déployer le paquet "pywebdriver-master", en attendant la publication.
Je suis très intéressé.

**Comment by alexis-via** [comment]
If you have an Epson TM-T20III with LAN interface, it supports ePOS, so I recommend to use pos_epson_printer https://github.com/odoo/odoo/tree/14.0/addons/pos_epson_printer and use direct printing. I just tested it with my new Epson TM-T20III with LAN and it works very well. You have to enable ePOS in the web interface of the printer, because it's not enabled by default.

**Comment by PierrickBrun** [comment]
The T20III is now supported in the .deb releases
