### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by aissaachraf** [akretion/pywebdriver#55]
Hi i Have  windows 10 as a client so how we can install the pywebdriver.

thx

**Comment by PierrickBrun** [comment]
Hi !

There is no clear distribution method for windows for now (we're working on making travis generate it but it is not working atm)

If you want to create a .zip you can do it with:
 - `git clone https://github.com/akretion/pywebdriver`
 - create yourself a virtualenv if you want
 - `pip install -r windows/requirements.txt`
 - `pip install pyinstaller`
 - `pyinstaller windows/pywebdriver.spec`

I'd recommend using python3.7, I think there are frictions with `netifaces` installation in python 3.8+.

Then you will have the pywebdriver.exe created in dist/pywebdriver. You can zip the folder and distribute the pywebdriver.zip to your client.

Bear in mind windows support is still experimental and not everything is working as good as on linux.

**Comment by PierrickBrun** [comment]
You will need to install the drivers separately, for instance:

libusbK for usb escpos: via https://zadig.akeo.ie/ 

you will also need to have a pdf reader to be able to print pdf's. Sumatra is easy to work with https://www.sumatrapdfreader.org/download-free-pdf-viewer.html

**Comment by flotho** [comment]
also related to #115
