### ISSUE TITLE
Printing a receipt from Odoo POS doesn't work on Odoo v13+

### ISSUE THREAD

**Issue by alexis-via** [akretion/pywebdriver#56]
Printing a receipt from Odoo POS via pywebdriver works well on Odoo v12, but doesn't work on odoo v13 nor v14 : the POS frontend always shows "Printer offline" in the top bar. When you look at the exchanges between POS frontend and pywebdriver, the request POST /hw_proxy/status_json receives

```
{
  "jsonrpc": "2.0", 
  "result": {
    "escpos": {
      "messages": [], 
      "status": "connected"
    }, 
    "telium": {
      "messages": [], 
      "status": "connected"
    }
  }
```

**Comment by alexis-via** [comment]
Part of the answer is in this commit on odoo : https://github.com/odoo/odoo/commit/03b2f7b77dc6189bb485e0b834dba5f6d3d4da2c
Removal of escpos. New calls to print a receipt (default_printer_action) that send the image of the receipt.

**Comment by PierrickBrun** [comment]
fixed here: https://github.com/akretion/pywebdriver/commit/6caa4c5b8daeabe901dea3978709bdab741d4a81 
Also, for the status to display correctly, this module will be needed: https://github.com/OCA/pos/pull/577
