### ISSUE TITLE
new release doesn't propose deb package

### ISSUE THREAD

**Issue by legalsylvain** [akretion/pywebdriver#71]
Hi. V3.0.3 contains a debian package (https://github.com/akretion/pywebdriver/releases/tag/v3.0.3)

however V3.0.4 or V3.0.5 doesn't contain any debian package.

@PierrickBrun : do you know why ? 

thanks !

**Comment by quentinDupont** [comment]
This issue is obsolete and can be closed :)

Debian package are released for any merge on master branch.
