### ISSUE TITLE
usb printer support on Linux broken

### ISSUE THREAD

**Issue by alexis-via** [akretion/pywebdriver#88]
With current master under Linux with TM-T20II USB :
- the printer first appear as connected
- then, it switches to disconnected because self.device is None

I went back to commit c7625f886f4ab0f3bfdf137caa05b6107f70d78f dated September 15 2021 and the bug is not present. So it's a recent bug.

**Comment by alexis-via** [comment]
I downgraded pyusb to the version supplied as debian packages in Ubuntu 20.04 (debian package "python3-usb" version 1.0.2-1build1), as a replacement of pyusb 1.2. It nows works fine with master.

**Comment by quentinDupont** [comment]
Can you specify the operation to do for people who do not know pywebdriver well? (me haha)

If you have to do a manual operation, it doesn't really seem to be a solved problem, does it?
